package com.mycompany.laberinto.frontend.principal;

import com.mycompany.laberinto.backend.ListaLaberintos;
import com.mycompany.laberinto.backend.NodoLaberinto;
import com.mycompany.laberinto.backend.edittablero.TableroParaCrearLaberinto;
import com.mycompany.laberinto.backend.generarlaberintos.GenerateMazeFromList;
import com.mycompany.laberinto.backend.util.ActualizarDatos;
import com.mycompany.laberinto.personajes.Jugador;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author saien
 */
public class LaberintoFrame extends javax.swing.JFrame implements ActualizarDatos{

    private ListaLaberintos lista = new ListaLaberintos();
    private TableroParaCrearLaberinto tablero;
    private ImageIcon gif;
    private static final String PATH_GIF = "com/mycompany/laberinto/images/laberinto2.gif";
    private JLabel lblGif;
    private Jugador jugador;
//    GenerateMazeFromList mazeFromList;
    
    public LaberintoFrame() {
        initComponents();
        jugador = new Jugador();
        gif = new ImageIcon(getClass().getClassLoader().getResource(PATH_GIF));
        lblGif = new JLabel(gif);
        lblGif.setBounds(0, 0, pnlInicio.getWidth(), pnlInicio.getHeight());

        pnlInicio.add(lblGif);
        setLocationRelativeTo(null);
    }

    //Metodo para llenar el combobox 
    private void llenarCombobox(JComboBox comboBox) {
        lista.cargarLaberintosDesdeArchivos();
        NodoLaberinto actual = lista.getInicio();
        //Ciclo que termina hasta que la ultima referencia apunte a null
        while (actual != null) {
            //Obtenemos el nombre
            String nameMaze = actual.getLaberinto().getNombre();
            //Agregamos el nombre al combobox
            comboBox.removeAllItems();
            comboBox.addItem(nameMaze);
            //Obtenemos la siguiente referencia
            actual = actual.getSiguiente();
        }
    }

    // Método para mostrar un panel específico
    public void mostrarPanel(String panelName) {
        CardLayout layout = (CardLayout) getContentPane().getLayout();
        layout.show(getContentPane(), panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInicio = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();
        btnEditorLaberintos = new javax.swing.JButton();
        btnRepeticiones = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        pnlInformacion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblOroJugador = new javax.swing.JLabel();
        lblOroSalida = new javax.swing.JLabel();
        lblItemInvencible = new javax.swing.JLabel();
        lblItemFantasma = new javax.swing.JLabel();
        pnlLaberinto = new javax.swing.JPanel();
        pnlPMenu = new javax.swing.JPanel();
        btnMenuPInfo = new javax.swing.JButton();
        pnlMakeMaze = new javax.swing.JPanel();
        pnlMakeMazeData = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtAnchoLaberinto = new javax.swing.JTextField();
        jtxtLargoLaberinto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtFilaMakeMaze = new javax.swing.JTextField();
        jtxtColumnaMakeMaze = new javax.swing.JTextField();
        btnGenerateMaze = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        rbtnCamino = new javax.swing.JRadioButton();
        rbtnPared = new javax.swing.JRadioButton();
        rbtnSalida = new javax.swing.JRadioButton();
        rbtnInicio = new javax.swing.JRadioButton();
        btnChangeCasilla = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jtxtOroSalir = new javax.swing.JTextField();
        rbtnOro = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jtxtVelocidadBots = new javax.swing.JTextField();
        rbtnLowSmartBot = new javax.swing.JRadioButton();
        rbtnHighSmartBot = new javax.swing.JRadioButton();
        btnSaveMazeCreated = new javax.swing.JButton();
        jtxtCantOroCasilla = new javax.swing.JTextField();
        btnCrearBot = new javax.swing.JButton();
        pnlCreatingMaze = new javax.swing.JPanel();
        pnlSelectMaze = new javax.swing.JPanel();
        jCBSelectPlayMaze = new javax.swing.JComboBox<>();
        btnPlayMazeSelected = new javax.swing.JButton();
        pnlMenu = new javax.swing.JPanel();
        btnMenuBack = new javax.swing.JLabel();
        btnMenuJugar = new javax.swing.JButton();
        btnMenuEditLaberinto = new javax.swing.JButton();
        btnMenuRepes = new javax.swing.JButton();
        btnMenuReportes = new javax.swing.JButton();
        btnMenuSalir = new javax.swing.JButton();
        pnlEditMaze = new javax.swing.JPanel();
        pnlCreatingMaze1 = new javax.swing.JPanel();
        pnlMakeMazeData1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtxtFilaEditMaze = new javax.swing.JTextField();
        jtxtColumnaEditMaze = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        rbtnEditMazeCamino = new javax.swing.JRadioButton();
        rbtnEditMazePared = new javax.swing.JRadioButton();
        rbtnEditMazeSalida = new javax.swing.JRadioButton();
        rbtnEditMazeInicio = new javax.swing.JRadioButton();
        btnEditMazeCasilla = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jtxtEditMazeOroSalir = new javax.swing.JTextField();
        rbtnEditMazeOro = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        jtxtEditMazeNumBots = new javax.swing.JTextField();
        rbtnEditMazeLowSmartBot = new javax.swing.JRadioButton();
        rbtnEditMazeHighSmartBot = new javax.swing.JRadioButton();
        btnSaveMazeEdited = new javax.swing.JButton();
        pnlMenuEditLab = new javax.swing.JPanel();
        btnMenuMakeMaze = new javax.swing.JButton();
        btnMenuEditMaze = new javax.swing.JButton();
        pnlSelectEditMaze = new javax.swing.JPanel();
        jCBEditMaze = new javax.swing.JComboBox<>();
        btnEditSelectMaze = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new java.awt.CardLayout());

        btnJugar.setBackground(new java.awt.Color(152, 53, 255));
        btnJugar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnJugar.setText("Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        btnEditorLaberintos.setBackground(new java.awt.Color(152, 53, 255));
        btnEditorLaberintos.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnEditorLaberintos.setForeground(new java.awt.Color(255, 255, 255));
        btnEditorLaberintos.setText("Editor Laberintos");
        btnEditorLaberintos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorLaberintosActionPerformed(evt);
            }
        });

        btnRepeticiones.setBackground(new java.awt.Color(152, 53, 255));
        btnRepeticiones.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnRepeticiones.setForeground(new java.awt.Color(255, 255, 255));
        btnRepeticiones.setText("Repeticiones");

        btnReportes.setBackground(new java.awt.Color(152, 53, 255));
        btnReportes.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Reportes");

        btnSalir.setBackground(new java.awt.Color(152, 53, 255));
        btnSalir.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(152, 53, 255));
        jLabel1.setFont(new java.awt.Font("Fira Code SemiBold", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/laberinto/images/titulo.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(269, 32));

        javax.swing.GroupLayout pnlInicioLayout = new javax.swing.GroupLayout(pnlInicio);
        pnlInicio.setLayout(pnlInicioLayout);
        pnlInicioLayout.setHorizontalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInicioLayout.createSequentialGroup()
                .addContainerGap(437, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(390, 390, 390))
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addGroup(pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInicioLayout.createSequentialGroup()
                        .addGap(596, 596, 596)
                        .addComponent(btnEditorLaberintos, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInicioLayout.createSequentialGroup()
                        .addGap(636, 636, 636)
                        .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInicioLayout.createSequentialGroup()
                        .addGap(623, 623, 623)
                        .addComponent(btnRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInicioLayout.createSequentialGroup()
                        .addGap(644, 644, 644)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInicioLayout.createSequentialGroup()
                        .addGap(639, 639, 639)
                        .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInicioLayout.setVerticalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnEditorLaberintos, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        getContentPane().add(pnlInicio, "Inicio");

        pnlPrincipal.setBackground(new java.awt.Color(0, 0, 0));

        pnlInformacion.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Oro:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fantasma: ");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Oro necesario:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Items");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Invencible: ");

        lblOroJugador.setBackground(new java.awt.Color(255, 255, 255));
        lblOroJugador.setForeground(new java.awt.Color(0, 0, 0));
        lblOroJugador.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        lblOroSalida.setBackground(new java.awt.Color(255, 255, 255));
        lblOroSalida.setForeground(new java.awt.Color(0, 0, 0));
        lblOroSalida.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        lblItemInvencible.setForeground(new java.awt.Color(255, 255, 255));
        lblItemInvencible.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        lblItemFantasma.setForeground(new java.awt.Color(255, 255, 255));
        lblItemFantasma.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout pnlInformacionLayout = new javax.swing.GroupLayout(pnlInformacion);
        pnlInformacion.setLayout(pnlInformacionLayout);
        pnlInformacionLayout.setHorizontalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlInformacionLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOroSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))
                    .addGroup(pnlInformacionLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOroJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItemInvencible, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItemFantasma, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(779, Short.MAX_VALUE))
        );
        pnlInformacionLayout.setVerticalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOroJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOroSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblItemInvencible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(lblItemFantasma, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pnlLaberinto.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlLaberintoLayout = new javax.swing.GroupLayout(pnlLaberinto);
        pnlLaberinto.setLayout(pnlLaberintoLayout);
        pnlLaberintoLayout.setHorizontalGroup(
            pnlLaberintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1465, Short.MAX_VALUE)
        );
        pnlLaberintoLayout.setVerticalGroup(
            pnlLaberintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );

        pnlPMenu.setBackground(new java.awt.Color(0, 0, 0));
        pnlPMenu.setPreferredSize(new java.awt.Dimension(1422, 50));

        btnMenuPInfo.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuPInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/laberinto/images/menu-color.png"))); // NOI18N
        btnMenuPInfo.setBorder(null);
        btnMenuPInfo.setBorderPainted(false);
        btnMenuPInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuPInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenuPInfo.setPreferredSize(new java.awt.Dimension(50, 50));
        btnMenuPInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPMenuLayout = new javax.swing.GroupLayout(pnlPMenu);
        pnlPMenu.setLayout(pnlPMenuLayout);
        pnlPMenuLayout.setHorizontalGroup(
            pnlPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1477, Short.MAX_VALUE)
            .addGroup(pnlPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPMenuLayout.createSequentialGroup()
                    .addComponent(btnMenuPInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1378, Short.MAX_VALUE)))
        );
        pnlPMenuLayout.setVerticalGroup(
            pnlPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pnlPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPMenuLayout.createSequentialGroup()
                    .addComponent(btnMenuPInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlLaberinto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlPMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1477, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(853, Short.MAX_VALUE)
                .addComponent(pnlInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPrincipalLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(pnlLaberinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(128, Short.MAX_VALUE)))
            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPrincipalLayout.createSequentialGroup()
                    .addComponent(pnlPMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 931, Short.MAX_VALUE)))
        );

        getContentPane().add(pnlPrincipal, "Principal");

        pnlMakeMaze.setBackground(new java.awt.Color(0, 0, 0));

        pnlMakeMazeData.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tamaño Laberinto");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Largo");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Ancho");

        jtxtAnchoLaberinto.setBackground(new java.awt.Color(255, 255, 255));
        jtxtAnchoLaberinto.setForeground(new java.awt.Color(0, 0, 0));

        jtxtLargoLaberinto.setBackground(new java.awt.Color(255, 255, 255));
        jtxtLargoLaberinto.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Elegir Casilla");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fila");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Columna");

        jtxtFilaMakeMaze.setBackground(new java.awt.Color(255, 255, 255));
        jtxtFilaMakeMaze.setForeground(new java.awt.Color(0, 0, 0));

        jtxtColumnaMakeMaze.setBackground(new java.awt.Color(255, 255, 255));
        jtxtColumnaMakeMaze.setForeground(new java.awt.Color(0, 0, 0));

        btnGenerateMaze.setBackground(new java.awt.Color(152, 53, 255));
        btnGenerateMaze.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnGenerateMaze.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateMaze.setText("Generar");
        btnGenerateMaze.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(152, 53, 255)));
        btnGenerateMaze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerateMaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateMazeActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tipo Casilla");

        rbtnCamino.setBackground(new java.awt.Color(0, 0, 0));
        rbtnCamino.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        rbtnCamino.setForeground(new java.awt.Color(255, 255, 255));
        rbtnCamino.setText("Camino");

        rbtnPared.setBackground(new java.awt.Color(0, 0, 0));
        rbtnPared.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        rbtnPared.setForeground(new java.awt.Color(255, 255, 255));
        rbtnPared.setText("Pared");

        rbtnSalida.setBackground(new java.awt.Color(0, 0, 0));
        rbtnSalida.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        rbtnSalida.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSalida.setText("Salida");

        rbtnInicio.setBackground(new java.awt.Color(0, 0, 0));
        rbtnInicio.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        rbtnInicio.setForeground(new java.awt.Color(255, 255, 255));
        rbtnInicio.setText("Inicio");

        btnChangeCasilla.setBackground(new java.awt.Color(152, 53, 255));
        btnChangeCasilla.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnChangeCasilla.setForeground(new java.awt.Color(255, 255, 255));
        btnChangeCasilla.setText("Aceptar");
        btnChangeCasilla.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(152, 53, 255)));
        btnChangeCasilla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangeCasilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeCasillaActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Bots");

        jtxtOroSalir.setBackground(new java.awt.Color(255, 255, 255));
        jtxtOroSalir.setForeground(new java.awt.Color(204, 204, 204));
        jtxtOroSalir.setText("Oro Requerido");
        jtxtOroSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtOroSalirMousePressed(evt);
            }
        });

        rbtnOro.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        rbtnOro.setForeground(new java.awt.Color(255, 255, 255));
        rbtnOro.setText("Oro");

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Velocidad");

        jtxtVelocidadBots.setBackground(new java.awt.Color(255, 255, 255));
        jtxtVelocidadBots.setForeground(new java.awt.Color(0, 0, 0));

        rbtnLowSmartBot.setBackground(new java.awt.Color(0, 0, 0));
        rbtnLowSmartBot.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        rbtnLowSmartBot.setForeground(new java.awt.Color(255, 255, 255));
        rbtnLowSmartBot.setText("Baja");

        rbtnHighSmartBot.setBackground(new java.awt.Color(0, 0, 0));
        rbtnHighSmartBot.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        rbtnHighSmartBot.setForeground(new java.awt.Color(255, 255, 255));
        rbtnHighSmartBot.setText("Alta");

        btnSaveMazeCreated.setBackground(new java.awt.Color(152, 53, 255));
        btnSaveMazeCreated.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSaveMazeCreated.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveMazeCreated.setText("Guardar");
        btnSaveMazeCreated.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(152, 53, 255)));
        btnSaveMazeCreated.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveMazeCreated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMazeCreatedActionPerformed(evt);
            }
        });

        jtxtCantOroCasilla.setBackground(new java.awt.Color(255, 255, 255));
        jtxtCantOroCasilla.setForeground(new java.awt.Color(0, 0, 0));

        btnCrearBot.setBackground(new java.awt.Color(152, 53, 255));
        btnCrearBot.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCrearBot.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearBot.setText("crear");
        btnCrearBot.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(152, 53, 255)));
        btnCrearBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearBotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMakeMazeDataLayout = new javax.swing.GroupLayout(pnlMakeMazeData);
        pnlMakeMazeData.setLayout(pnlMakeMazeDataLayout);
        pnlMakeMazeDataLayout.setHorizontalGroup(
            pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                        .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtAnchoLaberinto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtLargoLaberinto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(btnGenerateMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtColumnaMakeMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtFilaMakeMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(173, 173, 173)
                        .addComponent(jLabel10)))
                .addGap(79, 79, 79)
                .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                        .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnInicio)
                            .addComponent(rbtnSalida)
                            .addComponent(rbtnPared))
                        .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                                        .addComponent(rbtnOro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtCantOroCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                                        .addComponent(jtxtOroSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnChangeCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnCamino)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(207, 207, 207))
                    .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                        .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(7, 7, 7)
                                .addComponent(jtxtVelocidadBots, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                                .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnLowSmartBot)
                                    .addComponent(rbtnHighSmartBot))
                                .addGap(24, 24, 24)
                                .addComponent(btnCrearBot, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(btnSaveMazeCreated)
                        .addGap(25, 25, 25))))
        );
        pnlMakeMazeDataLayout.setVerticalGroup(
            pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                        .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMakeMazeDataLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnGenerateMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jtxtFilaMakeMaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jtxtAnchoLaberinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(jtxtColumnaMakeMaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jtxtLargoLaberinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rbtnInicio)
                                        .addComponent(rbtnCamino)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtnSalida)
                                    .addComponent(jtxtOroSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnChangeCasilla))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtnPared)
                                    .addComponent(rbtnOro)
                                    .addComponent(jtxtCantOroCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(4, 4, 4)
                            .addComponent(btnSaveMazeCreated, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jtxtVelocidadBots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMakeMazeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(rbtnLowSmartBot)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbtnHighSmartBot))
                                .addGroup(pnlMakeMazeDataLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCrearBot, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCreatingMaze.setBackground(new java.awt.Color(0, 0, 0));
        pnlCreatingMaze.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnlMakeMazeLayout = new javax.swing.GroupLayout(pnlMakeMaze);
        pnlMakeMaze.setLayout(pnlMakeMazeLayout);
        pnlMakeMazeLayout.setHorizontalGroup(
            pnlMakeMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1477, Short.MAX_VALUE)
            .addGroup(pnlMakeMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMakeMazeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlMakeMazeData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlMakeMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMakeMazeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlCreatingMaze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlMakeMazeLayout.setVerticalGroup(
            pnlMakeMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
            .addGroup(pnlMakeMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMakeMazeLayout.createSequentialGroup()
                    .addContainerGap(803, Short.MAX_VALUE)
                    .addComponent(pnlMakeMazeData, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(pnlMakeMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMakeMazeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlCreatingMaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(975, Short.MAX_VALUE)))
        );

        getContentPane().add(pnlMakeMaze, "MakeMaze");

        pnlSelectMaze.setBackground(new java.awt.Color(0, 0, 0));

        jCBSelectPlayMaze.setBackground(new java.awt.Color(0, 0, 0));
        jCBSelectPlayMaze.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jCBSelectPlayMaze.setForeground(new java.awt.Color(255, 255, 255));
        jCBSelectPlayMaze.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBSelectPlayMaze.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(152, 53, 255)));

        btnPlayMazeSelected.setBackground(new java.awt.Color(152, 53, 255));
        btnPlayMazeSelected.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnPlayMazeSelected.setForeground(new java.awt.Color(255, 255, 255));
        btnPlayMazeSelected.setText("Jugar");
        btnPlayMazeSelected.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(152, 53, 255)));
        btnPlayMazeSelected.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlayMazeSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayMazeSelectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSelectMazeLayout = new javax.swing.GroupLayout(pnlSelectMaze);
        pnlSelectMaze.setLayout(pnlSelectMazeLayout);
        pnlSelectMazeLayout.setHorizontalGroup(
            pnlSelectMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectMazeLayout.createSequentialGroup()
                .addGroup(pnlSelectMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSelectMazeLayout.createSequentialGroup()
                        .addGap(627, 627, 627)
                        .addComponent(btnPlayMazeSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSelectMazeLayout.createSequentialGroup()
                        .addGap(590, 590, 590)
                        .addComponent(jCBSelectPlayMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(602, Short.MAX_VALUE))
        );
        pnlSelectMazeLayout.setVerticalGroup(
            pnlSelectMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectMazeLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jCBSelectPlayMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191)
                .addComponent(btnPlayMazeSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(502, Short.MAX_VALUE))
        );

        getContentPane().add(pnlSelectMaze, "SelectMaze");

        pnlMenu.setBackground(new java.awt.Color(0, 0, 0));

        btnMenuBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMenuBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/laberinto/images/back.png"))); // NOI18N
        btnMenuBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuBackMousePressed(evt);
            }
        });

        btnMenuJugar.setBackground(new java.awt.Color(199, 91, 255));
        btnMenuJugar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMenuJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuJugar.setText("Jugar");
        btnMenuJugar.setBorder(null);
        btnMenuJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuJugarActionPerformed(evt);
            }
        });

        btnMenuEditLaberinto.setBackground(new java.awt.Color(199, 91, 255));
        btnMenuEditLaberinto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMenuEditLaberinto.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuEditLaberinto.setText("Editar Laberinto");
        btnMenuEditLaberinto.setBorder(null);
        btnMenuEditLaberinto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuEditLaberinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuEditLaberintoActionPerformed(evt);
            }
        });

        btnMenuRepes.setBackground(new java.awt.Color(199, 91, 255));
        btnMenuRepes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMenuRepes.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuRepes.setText("Repeticiones");
        btnMenuRepes.setBorder(null);
        btnMenuRepes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnMenuReportes.setBackground(new java.awt.Color(199, 91, 255));
        btnMenuReportes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMenuReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuReportes.setText("Reportes");
        btnMenuReportes.setBorder(null);
        btnMenuReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnMenuSalir.setBackground(new java.awt.Color(199, 91, 255));
        btnMenuSalir.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMenuSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuSalir.setText("Salir");
        btnMenuSalir.setBorder(null);
        btnMenuSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnMenuBack))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(545, 545, 545)
                        .addComponent(btnMenuEditLaberinto, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(566, 566, 566)
                        .addComponent(btnMenuRepes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(582, 582, 582)
                        .addComponent(btnMenuReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(612, 612, 612)
                        .addComponent(btnMenuSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(602, 602, 602)
                        .addComponent(btnMenuJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(718, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnMenuBack)
                .addGap(83, 83, 83)
                .addComponent(btnMenuJugar)
                .addGap(60, 60, 60)
                .addComponent(btnMenuEditLaberinto)
                .addGap(52, 52, 52)
                .addComponent(btnMenuRepes)
                .addGap(64, 64, 64)
                .addComponent(btnMenuReportes)
                .addGap(61, 61, 61)
                .addComponent(btnMenuSalir)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMenu, "Menu");

        pnlCreatingMaze1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlCreatingMaze1Layout = new javax.swing.GroupLayout(pnlCreatingMaze1);
        pnlCreatingMaze1.setLayout(pnlCreatingMaze1Layout);
        pnlCreatingMaze1Layout.setHorizontalGroup(
            pnlCreatingMaze1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1465, Short.MAX_VALUE)
        );
        pnlCreatingMaze1Layout.setVerticalGroup(
            pnlCreatingMaze1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );

        pnlMakeMazeData1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Elegir Casilla");

        jLabel20.setText("Fila");

        jLabel21.setText("Columna");

        jtxtFilaEditMaze.setBackground(new java.awt.Color(255, 255, 255));
        jtxtFilaEditMaze.setForeground(new java.awt.Color(0, 0, 0));

        jtxtColumnaEditMaze.setBackground(new java.awt.Color(255, 255, 255));
        jtxtColumnaEditMaze.setForeground(new java.awt.Color(0, 0, 0));

        jLabel22.setText("Tipo Casilla");

        rbtnEditMazeCamino.setText("Camino");

        rbtnEditMazePared.setText("Pared");

        rbtnEditMazeSalida.setText("Salida");

        rbtnEditMazeInicio.setText("Inicio");

        btnEditMazeCasilla.setBackground(new java.awt.Color(0, 0, 0));
        btnEditMazeCasilla.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnEditMazeCasilla.setForeground(new java.awt.Color(255, 255, 255));
        btnEditMazeCasilla.setText("Aceptar");
        btnEditMazeCasilla.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(152, 53, 255)));
        btnEditMazeCasilla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditMazeCasilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMazeCasillaActionPerformed(evt);
            }
        });

        jLabel23.setText("Bots");

        jtxtEditMazeOroSalir.setBackground(new java.awt.Color(255, 255, 255));
        jtxtEditMazeOroSalir.setForeground(new java.awt.Color(204, 204, 204));
        jtxtEditMazeOroSalir.setText("Oro Requerido");
        jtxtEditMazeOroSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtEditMazeOroSalirMousePressed(evt);
            }
        });

        rbtnEditMazeOro.setText("Oro");

        jLabel24.setText("Cantidad");

        jtxtEditMazeNumBots.setBackground(new java.awt.Color(255, 255, 255));
        jtxtEditMazeNumBots.setForeground(new java.awt.Color(0, 0, 0));

        rbtnEditMazeLowSmartBot.setText("Baja");

        rbtnEditMazeHighSmartBot.setText("Alta");

        btnSaveMazeEdited.setBackground(new java.awt.Color(0, 0, 0));
        btnSaveMazeEdited.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSaveMazeEdited.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveMazeEdited.setText("Guardar");
        btnSaveMazeEdited.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(152, 53, 255)));
        btnSaveMazeEdited.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveMazeEdited.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMazeEditedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMakeMazeData1Layout = new javax.swing.GroupLayout(pnlMakeMazeData1);
        pnlMakeMazeData1.setLayout(pnlMakeMazeData1Layout);
        pnlMakeMazeData1Layout.setHorizontalGroup(
            pnlMakeMazeData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMakeMazeData1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(pnlMakeMazeData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMakeMazeData1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtColumnaEditMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMakeMazeData1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtFilaEditMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(pnlMakeMazeData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(pnlMakeMazeData1Layout.createSequentialGroup()
                        .addGroup(pnlMakeMazeData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnEditMazeInicio)
                            .addComponent(rbtnEditMazeSalida)
                            .addComponent(rbtnEditMazePared))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMakeMazeData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtEditMazeOroSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditMazeCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMakeMazeData1Layout.createSequentialGroup()
                                .addComponent(rbtnEditMazeCamino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnEditMazeOro)))))
                .addGap(107, 107, 107)
                .addGroup(pnlMakeMazeData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnEditMazeLowSmartBot)
                    .addComponent(rbtnEditMazeHighSmartBot)
                    .addGroup(pnlMakeMazeData1Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(7, 7, 7)
                        .addComponent(jtxtEditMazeNumBots, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(btnSaveMazeEdited)
                .addGap(183, 183, 183))
        );
        pnlMakeMazeData1Layout.setVerticalGroup(
            pnlMakeMazeData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMakeMazeData1Layout.createSequentialGroup()
                .addGroup(pnlMakeMazeData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMakeMazeData1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlMakeMazeData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMakeMazeData1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMakeMazeData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtnEditMazeInicio)
                                    .addComponent(rbtnEditMazeCamino)
                                    .addComponent(rbtnEditMazeOro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMakeMazeData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtnEditMazeSalida)
                                    .addComponent(jtxtEditMazeOroSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMakeMazeData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtnEditMazePared)
                                    .addComponent(btnEditMazeCasilla)))
                            .addGroup(pnlMakeMazeData1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(25, 25, 25)
                                .addGroup(pnlMakeMazeData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jtxtFilaEditMaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMakeMazeData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(jtxtColumnaEditMaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMakeMazeData1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlMakeMazeData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMakeMazeData1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlMakeMazeData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(jtxtEditMazeNumBots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addComponent(rbtnEditMazeLowSmartBot))
                            .addComponent(btnSaveMazeEdited, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnEditMazeHighSmartBot)))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlEditMazeLayout = new javax.swing.GroupLayout(pnlEditMaze);
        pnlEditMaze.setLayout(pnlEditMazeLayout);
        pnlEditMazeLayout.setHorizontalGroup(
            pnlEditMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditMazeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCreatingMaze1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlEditMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEditMazeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlMakeMazeData1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlEditMazeLayout.setVerticalGroup(
            pnlEditMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditMazeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCreatingMaze1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
            .addGroup(pnlEditMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditMazeLayout.createSequentialGroup()
                    .addContainerGap(796, Short.MAX_VALUE)
                    .addComponent(pnlMakeMazeData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        getContentPane().add(pnlEditMaze, "EditMaze");

        pnlMenuEditLab.setBackground(new java.awt.Color(0, 0, 0));

        btnMenuMakeMaze.setBackground(new java.awt.Color(199, 91, 255));
        btnMenuMakeMaze.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMenuMakeMaze.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuMakeMaze.setText("Crear Laberinto");
        btnMenuMakeMaze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuMakeMaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMakeMazeActionPerformed(evt);
            }
        });

        btnMenuEditMaze.setBackground(new java.awt.Color(199, 91, 255));
        btnMenuEditMaze.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMenuEditMaze.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuEditMaze.setText("Editar Laberinto");
        btnMenuEditMaze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuEditMaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuEditMazeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuEditLabLayout = new javax.swing.GroupLayout(pnlMenuEditLab);
        pnlMenuEditLab.setLayout(pnlMenuEditLabLayout);
        pnlMenuEditLabLayout.setHorizontalGroup(
            pnlMenuEditLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuEditLabLayout.createSequentialGroup()
                .addContainerGap(627, Short.MAX_VALUE)
                .addComponent(btnMenuMakeMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(592, 592, 592))
            .addGroup(pnlMenuEditLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMenuEditLabLayout.createSequentialGroup()
                    .addGap(623, 623, 623)
                    .addComponent(btnMenuEditMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(591, Short.MAX_VALUE)))
        );
        pnlMenuEditLabLayout.setVerticalGroup(
            pnlMenuEditLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuEditLabLayout.createSequentialGroup()
                .addContainerGap(597, Short.MAX_VALUE)
                .addComponent(btnMenuMakeMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269))
            .addGroup(pnlMenuEditLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMenuEditLabLayout.createSequentialGroup()
                    .addGap(161, 161, 161)
                    .addComponent(btnMenuEditMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(710, Short.MAX_VALUE)))
        );

        getContentPane().add(pnlMenuEditLab, "MenuEditLab");

        pnlSelectEditMaze.setBackground(new java.awt.Color(0, 0, 0));

        jCBEditMaze.setBackground(new java.awt.Color(0, 0, 0));
        jCBEditMaze.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jCBEditMaze.setForeground(new java.awt.Color(255, 255, 255));
        jCBEditMaze.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBEditMaze.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(199, 91, 255)));
        jCBEditMaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEditMazeActionPerformed(evt);
            }
        });

        btnEditSelectMaze.setBackground(new java.awt.Color(0, 0, 0));
        btnEditSelectMaze.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnEditSelectMaze.setForeground(new java.awt.Color(255, 255, 255));
        btnEditSelectMaze.setText("Editar");
        btnEditSelectMaze.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(199, 91, 255)));
        btnEditSelectMaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSelectMazeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSelectEditMazeLayout = new javax.swing.GroupLayout(pnlSelectEditMaze);
        pnlSelectEditMaze.setLayout(pnlSelectEditMazeLayout);
        pnlSelectEditMazeLayout.setHorizontalGroup(
            pnlSelectEditMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectEditMazeLayout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addGroup(pnlSelectEditMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCBEditMaze, 0, 322, Short.MAX_VALUE)
                    .addComponent(btnEditSelectMaze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(696, Short.MAX_VALUE))
        );
        pnlSelectEditMazeLayout.setVerticalGroup(
            pnlSelectEditMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectEditMazeLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jCBEditMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 417, Short.MAX_VALUE)
                .addComponent(btnEditSelectMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );

        getContentPane().add(pnlSelectEditMaze, "MenuSelectEditLab");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        mostrarPanel("SelectMaze");
        llenarCombobox(jCBSelectPlayMaze);
    }//GEN-LAST:event_btnJugarActionPerformed

    private void jtxtOroSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtOroSalirMousePressed
        if (jtxtOroSalir.getText().equals("Oro Requerido")) {

            jtxtOroSalir.setText("");
            jtxtOroSalir.setForeground(Color.BLACK);

        }
    }//GEN-LAST:event_jtxtOroSalirMousePressed

    private void btnPlayMazeSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayMazeSelectedActionPerformed
        String laberintoSeleccionado = (String) jCBSelectPlayMaze.getSelectedItem();
        showMazeSelected(laberintoSeleccionado);
    }//GEN-LAST:event_btnPlayMazeSelectedActionPerformed

    private void btnGenerateMazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateMazeActionPerformed
        construirTablero();
    }//GEN-LAST:event_btnGenerateMazeActionPerformed

    private void btnChangeCasillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeCasillaActionPerformed
        repintarTablero();
    }//GEN-LAST:event_btnChangeCasillaActionPerformed

    private void btnSaveMazeCreatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMazeCreatedActionPerformed
        String nombreLaberinto = JOptionPane.showInputDialog(this, "Ingrese un nombre para el Laberinto");
        int opcion = JOptionPane.showConfirmDialog(this, "Está seguro que desea crear el Laberinto?");
        if (opcion == JOptionPane.YES_OPTION) {
        tablero.guardarLaberinto(lista, nombreLaberinto);
        }else{
            
        }
    }//GEN-LAST:event_btnSaveMazeCreatedActionPerformed

    private void btnEditMazeCasillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMazeCasillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMazeCasillaActionPerformed

    private void jtxtEditMazeOroSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEditMazeOroSalirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEditMazeOroSalirMousePressed

    private void btnSaveMazeEditedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMazeEditedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveMazeEditedActionPerformed

    private void btnCrearBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearBotActionPerformed
        int velocidadBot = Integer.parseInt(jtxtVelocidadBots.getText());
        tablero.guardarBot(velocidadBot);
    }//GEN-LAST:event_btnCrearBotActionPerformed

    private void btnEditorLaberintosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorLaberintosActionPerformed
        mostrarPanel("MenuEditLab");
    }//GEN-LAST:event_btnEditorLaberintosActionPerformed

    private void btnMenuEditMazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEditMazeActionPerformed
        mostrarPanel("MenuSelectEditLab");
    }//GEN-LAST:event_btnMenuEditMazeActionPerformed

    private void btnMenuMakeMazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMakeMazeActionPerformed
        mostrarPanel("MakeMaze");
    }//GEN-LAST:event_btnMenuMakeMazeActionPerformed

    private void jCBEditMazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEditMazeActionPerformed
        llenarCombobox(jCBEditMaze);
    }//GEN-LAST:event_jCBEditMazeActionPerformed

    private void btnEditSelectMazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSelectMazeActionPerformed
        mostrarPanel("EditMaze");
    }//GEN-LAST:event_btnEditSelectMazeActionPerformed

    private void btnMenuPInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPInfoActionPerformed
        mostrarPanel("Menu");
    }//GEN-LAST:event_btnMenuPInfoActionPerformed

    private void btnMenuBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuBackMousePressed
        mostrarPanel("Principal");
    }//GEN-LAST:event_btnMenuBackMousePressed

    private void btnMenuJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuJugarActionPerformed
        mostrarPanel("SelectMaze");
    }//GEN-LAST:event_btnMenuJugarActionPerformed

    private void btnMenuEditLaberintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEditLaberintoActionPerformed
        mostrarPanel("MenuEditLab");
    }//GEN-LAST:event_btnMenuEditLaberintoActionPerformed

    private void btnMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnMenuSalirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void showMazeSelected(String name) {
        pnlLaberinto.removeAll();
        GenerateMazeFromList mazeFromList = new GenerateMazeFromList(lista, name, jugador);
        mazeFromList.setSize(pnlLaberinto.getWidth(), pnlLaberinto.getHeight());
        pnlLaberinto.add(mazeFromList, BorderLayout.CENTER);
        mostrarPanel("Principal");
        GenerateMazeFromList lab = (GenerateMazeFromList) pnlLaberinto.getComponent(0);
        lab.requestFocusInWindow();
        pnlLaberinto.revalidate();
        pnlLaberinto.repaint();
    }

    private void construirTablero() {
        int x, y;

        x = Integer.parseInt(jtxtLargoLaberinto.getText());
        y = Integer.parseInt(jtxtAnchoLaberinto.getText());
        tablero = new TableroParaCrearLaberinto(y, x);
        tablero.setVisible(true);
        limpiarCreadorLaberinto();

    }

    private void repintarTablero() {
        int x, y;

        x = Integer.parseInt(jtxtColumnaMakeMaze.getText());
        y = Integer.parseInt(jtxtFilaMakeMaze.getText());
        if (rbtnCamino.isSelected()) {
            tablero.aplicarCasillaCamino(y, x, 1);
        } else if (rbtnPared.isSelected()) {
            tablero.aplicarCasillaPared(y, x, 2);
        }else if (rbtnInicio.isSelected()){
            tablero.aplicarCasillaInicio(y, x, 3);
        }else if (rbtnSalida.isSelected()){
            int cantOroSalida = Integer.parseInt(jtxtOroSalir.getText());
            tablero.aplicarCasillaSalida(y, x, 4, cantOroSalida);
        }else if (rbtnOro.isSelected()){
            int cantOroCasilla = Integer.parseInt(jtxtCantOroCasilla.getText());
            tablero.aplicarCasillaOro(y, x, 5, cantOroCasilla);
        }
        limpiarCreadorLaberinto();
    }

    private void limpiarCreadorLaberinto() {
        pnlCreatingMaze.removeAll();
        pnlCreatingMaze.add(tablero, BorderLayout.CENTER);
        pnlCreatingMaze.revalidate();
        pnlCreatingMaze.repaint();
    }
    
        @Override
    public void actualizar() {
        lblOroJugador.setText(String.format("%s", jugador.getOro()));
//        lblOroSalida.setText(String.format("%s", mazeFromList.getOroSalida()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeCasilla;
    private javax.swing.JButton btnCrearBot;
    private javax.swing.JButton btnEditMazeCasilla;
    private javax.swing.JButton btnEditSelectMaze;
    private javax.swing.JButton btnEditorLaberintos;
    private javax.swing.JButton btnGenerateMaze;
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel btnMenuBack;
    private javax.swing.JButton btnMenuEditLaberinto;
    private javax.swing.JButton btnMenuEditMaze;
    private javax.swing.JButton btnMenuJugar;
    private javax.swing.JButton btnMenuMakeMaze;
    private javax.swing.JButton btnMenuPInfo;
    private javax.swing.JButton btnMenuRepes;
    private javax.swing.JButton btnMenuReportes;
    private javax.swing.JButton btnMenuSalir;
    private javax.swing.JButton btnPlayMazeSelected;
    private javax.swing.JButton btnRepeticiones;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSaveMazeCreated;
    private javax.swing.JButton btnSaveMazeEdited;
    private javax.swing.JComboBox<String> jCBEditMaze;
    private javax.swing.JComboBox<String> jCBSelectPlayMaze;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtxtAnchoLaberinto;
    private javax.swing.JTextField jtxtCantOroCasilla;
    private javax.swing.JTextField jtxtColumnaEditMaze;
    private javax.swing.JTextField jtxtColumnaMakeMaze;
    private javax.swing.JTextField jtxtEditMazeNumBots;
    private javax.swing.JTextField jtxtEditMazeOroSalir;
    private javax.swing.JTextField jtxtFilaEditMaze;
    private javax.swing.JTextField jtxtFilaMakeMaze;
    private javax.swing.JTextField jtxtLargoLaberinto;
    private javax.swing.JTextField jtxtOroSalir;
    private javax.swing.JTextField jtxtVelocidadBots;
    private javax.swing.JLabel lblItemFantasma;
    private javax.swing.JLabel lblItemInvencible;
    private javax.swing.JLabel lblOroJugador;
    private javax.swing.JLabel lblOroSalida;
    private javax.swing.JPanel pnlCreatingMaze;
    private javax.swing.JPanel pnlCreatingMaze1;
    private javax.swing.JPanel pnlEditMaze;
    private javax.swing.JPanel pnlInformacion;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPanel pnlLaberinto;
    private javax.swing.JPanel pnlMakeMaze;
    private javax.swing.JPanel pnlMakeMazeData;
    private javax.swing.JPanel pnlMakeMazeData1;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMenuEditLab;
    private javax.swing.JPanel pnlPMenu;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSelectEditMaze;
    private javax.swing.JPanel pnlSelectMaze;
    private javax.swing.JRadioButton rbtnCamino;
    private javax.swing.JRadioButton rbtnEditMazeCamino;
    private javax.swing.JRadioButton rbtnEditMazeHighSmartBot;
    private javax.swing.JRadioButton rbtnEditMazeInicio;
    private javax.swing.JRadioButton rbtnEditMazeLowSmartBot;
    private javax.swing.JRadioButton rbtnEditMazeOro;
    private javax.swing.JRadioButton rbtnEditMazePared;
    private javax.swing.JRadioButton rbtnEditMazeSalida;
    private javax.swing.JRadioButton rbtnHighSmartBot;
    private javax.swing.JRadioButton rbtnInicio;
    private javax.swing.JRadioButton rbtnLowSmartBot;
    private javax.swing.JRadioButton rbtnOro;
    private javax.swing.JRadioButton rbtnPared;
    private javax.swing.JRadioButton rbtnSalida;
    // End of variables declaration//GEN-END:variables


}
